### ISSUE TITLE
PetWalkCommand throws Fatal error. 0xC0000005

### ISSUE THREAD

**Issue by plsfixrito** [Rutherther/NosSmooth.Local#16]
```C#
Fatal error. 0xC0000005
   at NosSmooth.LocalBinding.Hooks.Implementations.PetWalkHook+<>c__DisplayClass7_0.<WrapWithCalling>b__0(UIntPtr, Int32, Int16, Int32)
   at NosSmooth.LocalBinding.Hooks.Implementations.PetWalkHook.<get_WrapperFunction>b__6_0(NosSmooth.LocalBinding.Structs.PetManager, UInt16, UInt16)
   at NosSmooth.LocalClient.CommandHandlers.Walk.PetWalkCommandHandler+<>c__DisplayClass8_1.<HandleCommand>b__2()
   at NosSmooth.LocalClient.UserActionDetector.NotUserAction[[Remora.Results.Result`1[[System.Boolean, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Remora.Results, Version=7.2.3.0, Culture=neutral, PublicKeyToken=null]](System.Func`1<Remora.Results.Result`1<Boolean>>)
   at NosSmooth.LocalClient.CommandHandlers.Walk.PetWalkCommandHandler+<>c__DisplayClass8_1.<HandleCommand>b__1()
   at NosSmooth.LocalBinding.NosThreadSynchronizer+<>c__DisplayClass14_0`1[[System.Boolean, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<SynchronizeAsync>b__0()
   at NosSmooth.LocalBinding.NosThreadSynchronizer.ExecuteOperation(SyncOperation)
   at NosSmooth.LocalBinding.NosThreadSynchronizer.PeriodicCall(System.Object, System.EventArgs)
   at NosSmooth.Extensions.SharedBinding.Hooks.SingleHook`3[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].FireCalled(System.Object, System.__Canon)
   at NosSmooth.LocalBinding.Hooks.Implementations.PeriodicHook.Detour()
```

**Comment by Rutherther** [comment]
Oops, you are right. I forgot to test that after rewriting hooks. Should be fixed now. There was a missing argument that is supposed to go on stack and that caused the exception.

Let me know if it still doesn't work for you.

**Comment by Rutherther** [comment]
There is also one more issue, the arrow telling you where you are going currently does not work for petwalk correctly, I am not sure why that is and I do not have enough time to investigate that now. I think it shouldn't be a problem.

**Comment by plsfixrito** [comment]
> Oops, you are right. I forgot to test that after rewriting hooks. Should be fixed now. There was a missing argument that is supposed to go on stack and that caused the exception.
> 
> Let me know if it still doesn't work for you.

Tested, now it works.

**Comment by Rutherther** [comment]
Just so you know, PetWalkCommand and PlayerWalkCommand are like clicking on a map, it will not get you anywhere on the map, usually only when there is not many obstacles. For getting anywhere on the map, pathfinding algorithm has to be used. I have made `NosSmooth.Extensions.Pathfinding` for that. Currently it does not fully support mates, but at least player walk should be fine.
